---
title: "gene_set_defs"
author: "Joshua Schmidt"
date: "10/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, echo=FALSE}
library(data.table)
```


## Get VIPs
```{r VIPs, echo=FALSE}
htvips <- fread("ht_vips.txt")
ltvips <- fread("lt_vips.txt",col.names = c("ens_id","interactions"))
```

#### have to get ens ids for ltvips and htvips
```{r ens ids for ltvips, cache=TRUE}
fwrite(x=ltvips[,.(ens_id)],
       file="../gene_annotations/ltvips_ensIds.txt",
       sep="\n",
       quote=F,
       col.names = F,
       row.names = F
)
fwrite(x=htvips[,.(all)],
       file="../gene_annotations/htvips_ensIds.txt",
       sep="\n",
       quote=F,
       col.names = F,
       row.names = F
)

fwrite(x=htvips[,.(all)],
       file="../gene_annotations/htvips_ensIds.txt",
       sep="\n",
       quote=F,
       col.names = F,
       row.names = F
)
```

```{bash, cache=TRUE}
cat ../gene_annotations/htvips_ensIds_gene.names.txt ../gene_annotations/ltvips_ensIds_gene.names.txt | sort | uniq | sed '/stable/d' > ../gene_annotations/allvips_ensIds_gene.names.txt
```


## Gene definitions
```{r}
genes <- fread(input = "../gene_annotations/hg19_nonRedundant_GOWINDA_noORS.bed",col.names = c("chr","start","end","name"))

ens_name <- fread("../gene_annotations/allvips_ensIds_gene.names.txt", col.names = c("ens_id","name"))
genes <-  genes[ens_name,on=.(name)][!chr%in% NA][!ens_id %in% NA]
```

```{r refine VIPS}
ltvips <- ltvips[genes,on=.(ens_id)]
ltvips[,interactions:=toupper(interactions)]
# viruses in the ltvips
ltviruses <- fread("../gene_annotations/lt_vips_vviruses.txt",header=FALSE)
ltviruses <- ltviruses[!grep(pattern = "SSRNART|ssRNART|dsRNA|dsDNA|dsrna|dsdna|ssRNA|ssrna|ssDNA|ssdna|^rna|^dna",V1,)]

lt_names <- toupper(ltviruses$V1)

ht_names <- names(htvips)[2:length(names(htvips))]
ht_names[2] <- "CORONAVIRUS"
names(htvips)[3] <- "CORONAVIRUS"

#-- make tables
vipDT_gowinda <- data.table()
vipDT_long <- data.table()
vipcount = 0
for (htv in ht_names){
  vipcount = vipcount+1
  htv_g <- genes[ens_id %in% htvips[,.(get(htv))][grep("ENSG",V1)]$V1]$name
  ltv_g <- ltvips[grep(pattern = htv,x=interactions)]$name
  all_g <- unique(sort(c(htv_g,ltv_g)))
  if (length(all_g >=1)) {
    tmpDT <- data.table(cat=paste0("vip:",sprintf("%07d", vipcount)),
                      name=htv,
                      genes=paste(all_g,collapse = " "))
    vipDT_gowinda <- rbindlist(list(vipDT_gowinda,tmpDT))
    tmpDT <- data.table(id=paste0("vip:",sprintf("%07d", vipcount)),
                      name=htv,
                      feature=all_g)
    vipDT_long <- rbindlist(list(vipDT_long,tmpDT))
  }
}



```


```{r write vip tables}
fwrite(vipDT_gowinda,file="../gene_sets/vips_GOWINDAformat.txt",sep="\t",col.names = F,row.names = F,quote = F)
fwrite(vipDT_long,file="../gene_sets/vips_long.txt",sep="\t",col.names = T,row.names = F,quote = F)

```

```{r KEGG}
library(jsonlite)
file="../gene_annotations/hsa00001.json"
document <- fromJSON(txt=file,flatten = T)

# from hgnc... to define ens to ncbi mapping. otherwise it is a mess!
# https://biomart.genenames.org/martform/#!/default/HGNC?datasets=hgnc_gene_mart&attributes=hgnc_gene__approved_symbol_1010%2Chgnc_gene__approved_name_1010%2Chgnc_gene__ensembl_gene__ensembl_gene_id_104%2Chgnc_gene__ncbi_gene__gene_id_1026&hgnc_gene__locus_group_1010=protein-coding+gene&hgnc_gene__status_1010=Approved

hgnc <- fread("../gene_annotations/hgnc.biomart.txt",select = c("Approved symbol","NCBI gene ID","Ensembl gene ID"),col.names = c("geneidA","ncbiid","ens"),header=T)
hgnc[duplicated(ens)]
# ENSG00000255374
hgnc[ens==hgnc[duplicated(ens)]$ens,geneidA]
# [1] "TAS2R43" "TAS2R45"
# already defind go genes
genes <- fread("data-raw/hg19_nonredundant_noORS.gene.ens.txt",col.names = c("geneidA","ens"),header=F)

genes[ens==hgnc[duplicated(ens)]$ens]$geneidA
# [1] "TAS2R43"
hgnc <- hgnc[!ens=="TAS2R45"]
genes <- genes[hgnc,on=.(ens)][,.(geneidA,ens,ncbiid)]
# so now have a consistent 1-1 mapping
# write out ens ids from HGNC. bo to ensembl biomart hg10=9 and get gene coordinates for these!
write.table(hgnc[,ens],file="data-raw/hgnc.ens.txt",sep="\n",col.names = F,row.names = F,quote = F)

# got ens gene defs....
hgnc.ens.defs <- fread("data-raw/hgnc.biomart.ens.chr.s.e.txt",col.names = c("ens","chr","start","end"))
# get them all?
hgnc[!ens %in% hgnc.ens.defs$ens]
# 287 missing...
# this time use HGNC symbols and try again....
write.table(hgnc[!ens %in% hgnc.ens.defs$ens][,geneidA],file="data-raw/hgnc.ens.intitally.missingtxt",sep="\n",col.names = F,row.names = F,quote = F)

hgnc.ens.defs2 <- fread("data-raw/hgnc.biomart.ens.chr.s.e.initially.missing.txt",col.names = c("ens","chr","start","end","geneidA"))
hgnc.ens.defs2 <- hgnc.ens.defs2[geneidA %in% hgnc$geneidA]

hgnc.ens.defs <- rbindlist(list(hgnc.ens.defs,hgnc.ens.defs2[,.(ens,chr,start,end)]))
# filter for autosomes
hgnc.ens.defs <- hgnc.ens.defs[chr %in% 1:22]
hgnc.ens.defs <- hgnc[hgnc.ens.defs,on=.(ens)][!geneidA %in% NA][!ncbiid %in% NA][order(geneidA)]





all.kegg.genes.map <- data.table()
for (i in seq_along(document$children$children)){
  tmp <- document$children$children[[i]]
  for(j in seq_along(tmp$children)){
    for(k in seq_along(tmp$children[[j]]$name)){
      description <- strsplit(tmp$children[[j]]$name[k]," ")[[1]]
      keggid <- strsplit(description[length(description)],split = ":|]")[[1]][2]
      name <- paste(description[-length(description)][-1],collapse = "_")
      for(g in seq_along(tmp$children[[j]]$children[[k]]$name)){
        geneinfo <- strsplit(tmp$children[[j]]$children[[k]]$name[g], " |;")[[1]]
        dt <- data.table(keggid, name,ncbiid=as.integer(geneinfo[1]),geneid=geneinfo[2])
        all.kegg.genes.map <- rbindlist(list(all.kegg.genes.map,dt))
      }
    }
  }
}
# genes wiht more than one ncbi id?
unique(all.kegg.genes.map[,.(ncbiid,geneid)])[,.N,by=geneid][N > 1]
# geneid N
# 1:    CYP2D6 2
# 2:  putative 4
# 3:      ICOS 2
# 4: olfactory 4

# olfactory and putative are nonsense
all.kegg.genes.map <- all.kegg.genes.map[!geneid %in% c("olfactory", "putative") ]

# for CYP2D6 and ICOS, correct ids are 1565 and 29851
unique(all.kegg.genes.map[,.(ncbiid,geneid)])[grep("CYP2D6",geneid)]
# ncbiid geneid
# 1:      1565 CYP2D6
# 2: 107987479 CYP2D6
unique(all.kegg.genes.map[,.(ncbiid,geneid)])[grep("^ICOS$",geneid)]
# ncbiid geneid
# 1: 102723996   ICOS
# 2:     29851   ICOS

all.kegg.genes.map <- all.kegg.genes.map[!ncbiid %in% c("102723996", "107987479") ]



unique(all.kegg.genes.map[,.(ncbiid,geneid)])[,.N,by=geneid][N > 1]
# empty
# so a unique gene name - ncbi mapping
# how many genes in
# total rows
# 46705
all.kegg.genes.map <- all.kegg.genes.map[genes,on=.(ncbiid)]
all.kegg.genes.map <- all.kegg.genes.map[!keggid %in% NA]

all.kegg.genes.map <- unique(all.kegg.genes.map[!gene %in% NA,.(id=keggid,name,gene=geneidA)])
setkey(all.kegg.genes.map,gene)
```

